#!/usr/bin/env node

const Migrate = require("migrate-js");
const mysql = require("mysql");

const db = mysql.createConnection(/* insert your connection param */);

const migrate = new Migrate({
    stateManager: "mysql",
    migrationsDirectory: process.join(__dirname, "migrations"),
    db,
});

migrate.up().then((migrations) => {
  console.log(`Successfully ran ${migrations.length} migrations`);
  db.end();
}).catch((err) => {
  db.end();
  throw err;
});