#!/usr/bin/env sh

../../bin/migrate-js --state-manager mysql \
                     --mysql-host localhost \
                     --mysql-port 3306 \
                     --mysql-database migratejs \
                     --mysql-user migratejs \
                     up
